version: '3'

services: 
  db:
    image: "mysql:latest"
    container_name: "db"
    ports: 
      - "3366:3306"
    hostname: "db"
    
    volumes: 
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'

    networks:
      netgroup:
        ipv4_address: 129.16.119.110
  
  web_api:
    build: ./web_api
    container_name: "web_api"
    ports: 
      - "8000:8000"
    privileged: true
    hostname: "web_api"

    volumes: 
      - ./web_api:/usr/web_api

    networks:
      netgroup:
        ipv4_address: 129.16.119.111

    command: python /usr/web_api/v1/server.py

  front:
    build: ./front
    container_name: "front"
    ports: 
      - "3000:3000"
    privileged: true
    stdin_open: true
    hostname: "front"

    volumes: 
      - ./front:/usr/front

    networks:
      netgroup:
        ipv4_address: 129.16.119.112

    command: sh -c "yarn build"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./front/wonder-scale/build:/var/www
      - ./web_server/nginx:/etc/nginx/conf.d/
    
    depends_on:
      - front
    
    networks:
      netgroup:
        ipv4_address: 129.16.119.113
  
networks:
  netgroup:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 129.16.0.0/16