apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web-api-claim0
  name: web-api-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
status: {}
